language: python
python:
  - "3.6"

env:
  - DJANGO=2.2.3

services:
  - docker

before_install:
  - python --version
  - pip install codecov
  - cd app

install:
  - pip install coverage
  - pip install codeclimate-test-reporter
  - pip install coveralls
  - pip install django

before_script: pip install docker-compose

script:
  - docker-compose run --rm app sh -c "python manage.py test && flake8"
  - python manage.py migrate
  - coverage run manage.py test


after_success:
  - CODECLIMATE_REPO_TOKEN=89d9aa84b39a2a2c82cf27e0b03c349311d84b5cf1d65f7dc8ef9dea48cf8b34 codeclimate-test-reporter --file .coverage
  - coverage report